# Generated by Django 6.1 on 2026-08-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(db_column='member_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('login_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('role', models.CharField(choices=[('STUDENT', '학생'), ('ADMIN', '관리자')], default='STUDENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
